# Generated by Django 3.2 on 2022-03-20 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_blogcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='parent',
        ),
    ]
