# Generated by Django 3.2 on 2022-03-21 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_remove_blogcomment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='post',
        ),
    ]
